tcp:
  host: "0.0.0.0"        # IP address of the TCP server,local PC, Not HOLOLENS!!!!!
  port: 8848                   # Port number for the TCP connection

saving:
  output_dir: "guiji_qingyi_3" # Directory where output data will be saved

skeleton:
  use_dual_camera: false       # Whether to use dual cameras for skeleton tracking
  T_M:                         # Transformation matrix (e.g., from camera to world coordinate system)
    [[1, 0, 0, 0],
     [0, -1, 0, 0],
     [0, 0, -1, 0],
     [0, 0, 0, 1]]

pointcloud:
  max_points: 8000             # Maximum number of points in the point cloud
  ero_para: 1                  # Erosion parameter used in point cloud filtering
  use_dual_camera: false       # Whether to use dual cameras for point cloud generation

alignment:
  aruco_path: "ROS_points.txt"
                                # Path to the ArUco calibration file (used for camera pose estimation)
  tm_cache_file: 'tm_matrix.txt'
  stereo_transform_path: "D:/Documents/MasterThesis/Tongli_Zhu_MSc/AR-MoCap/02_Code/02_PC/Python/PythonProject/Matlab/T_icp_updated.txt"
                                # Path to the stereo transformation matrix (T_Stereo), used to align both camera views

robot:
  position_file: "robotPosition.txt" # File containing robot position data

recording:
  output_file: "calibration_data_recorded.txt" # File to save recorded calibration data

handeyecalibration:
  EE_T_C:                        # End-effector to camera transformation matrix (T_EE_C)
    [
      [0.7072116574444889, -0.7068948956595069, 0.01229951483408578, 0.0055638825109295045],
      [0.706923115281596, 0.706766158549325, -0.02722693904929184, -0.0410967451426544],
      [0.010553703387069666, 0.02795002003515388, 0.9995536082296199, -0.03775071685436837],
      [0.0, 0.0, 0.0, 1.0]
    ] 